displayName: Web Authentification
type: middleware

import: github.com/antux18/web-auth-plugin

summary: "Plugin Traefik pour le TP3 d'Administration des Syst√®mes"

testData:
  Headers:
    X-URL: '{{URL}}'
